const Portfolio_data = [
  {
    id: 1,
    category: "Backend Developer",
    // totalLike: "Backend",
    title: "Restaurant Managment System Application in Laravel ",
    image: "./projects/Restaurant-Management.png",
    f1: "1-The process of creating an account for the customer and enjoying its powers.",
    f2: "2-Presenting restaurant meals to the customer.",
    f3: "3-Make reservations for the customer and create a reservation for the customer in the restaurant.",
    f4: "4-Show the home page of the customer.",
    f5: "5-admin login - Accountant login",
    f6: "6-Operations of adding, modifying, deleting and displaying the types of meals and meals.",
    f7: "7-Management processes for reservations.",
    f8: "8-Accounts management operations for accountants.",
    f9: "9-Store management operations in the restaurant.",
    f10: "10-Bring out the statistics for the profit and loss rate in the previous months for the restaurant.",
    f11: "11-Managing reservations for the restaurant by the accountant.",
    f12: "12-Export customer orders invoices.",
  },
  {
    id: 2,
    category: "Backend Developer",
    // totalLike: "750",
    title: "Real Time Chat Application in Laravel Livewire ",
    image: "./projects/Chat-PNG-HD.png",
    f1: "1-User logins.",
    f2: "2-Users view of the application.",
    f3: "3-Send a message.",
    f4: "4-Send a picture.",
    f5: "5-Send files",
    f6: "",
    f7: "",
    f8: "",
    f9: "",
    f10: "",
    f11: "",
    f12: "",
  },
  {
    id: 3,
    category: "Backend Developer",
    // totalLike: "630",
    title: "Chart Data Visulization Application in Laravel ",
    image: "./projects/chart Data visulizations.png",

    f1: "1-User logins.",
    f2: "2-Users view of the application.",
    f3: "3-Send a message.",
    f4: "4-Send a picture.",
    f5: "5-Send files",
    f6: "",
    f7: "",
    f8: "",
    f9: "",
    f10: "",
    f11: "",
    f12: "",
  },
  {
    id: 4,
    category: "Backend Developer",
    // totalLike: "360",
    title: "Invoicing System Application in Laravel",
    image: "./projects/invoices.jpeg",
    f1: "1-Customer login.",
    f2: "2-View statistical data and control panel.",
    f3: "3-The operations of adding, modifying, deleting and displaying the invoice.",
    f4: "4-Archiving and transferring invoices cases.",
    f5: "5-Reporting processes for employees' managers",
    f6: "6-Operations of addition, modification, deletion and presentation to banks.",
    f7: "7-Operations of adding, modifying, deleting and displaying sections for banks.",
    f8: "8-Operations of adding, modifying, deleting, displaying to users and creating accounts for them.",
    f9: "9-Assigning tasks and powers and separating them for assignment to the establishing employees.",
    f10: "10-Upload and delete attachments to invoices.",
    f11: "",
    f12: "",
  },
  {
    id: 5,
    category: "Backend Developer",
    // totalLike: "280",
    title: "Rest Full API Application in Laravel CRUD and JWT Authuntication",
    image: "./projects/Api.png",
    f1: "1-Create a product.",
    f2: "2-Update a product.",
    f3: "3-View the product.",
    f4: "4-Delete the product.",
    f5: "5-View all products",
    f6: "6-Use JWT of the for authorization and authentication.",
    f7: "",
    f8: "",
    f9: "",
    f10: "",
    f11: "",
    f12: "",
  },
  {
    id: 6,
    category: "Backend Developer",
    // totalLike: "690",
    title: "School Managment System Application in Laravel",
    image: "./projects/Schools.jpg",
    f1: "",
    f2: "",
    f3: "",
    f4: "",
    f5: "",
    f6: "",
    f7: "",
    f8: "",
    f9: "",
    f10: "",
    f11: "",
    f12: "",
  },
  {
    id: 7,
    category: "Backend Developer",
    // totalLike: "690",
    title: "Portfolio Dynamically System Application in Laravel",
    image: "./projects/portfolio.jpeg",
    f1: "",
    f2: "",
    f3: "",
    f4: "",
    f5: "",
    f6: "",
    f7: "",
    f8: "",
    f9: "",
    f10: "",
    f11: "",
    f12: "",
  },
  {
    id: 8,
    category: "Frontend Developer",
    // totalLike: "690",
    title: "Chat Application in React & Firebase",
    image: "./projects/chat React.png",
    f1: "1-Create a user through Google or with his information",
    f2: "2-Report to the manager",
    f3: "3-Send a message, file or photo",
    f4: "4-Show users to the manager",
    f5: "",
    f6: "",
    f7: "",
    f8: "",
    f9: "",
    f10: "",
    f11: "",
    f12: "",
  },
  {
    id: 9,
    category: "Frontend Developer",
    // totalLike: "690",
    title: "Shopping View in React ",
    image: "./projects/shopping.jpg",
    f1: "1-Create a product display page",
    f2: "2-Select the product",
    f3: "3-Gather the required products",
    f4: "4-Determining the invoice price",
    f5: "",
    f6: "",
    f7: "",
    f8: "",
    f9: "",
    f10: "",
    f11: "",
    f12: "",
  },
  {
    id: 10,
    category: "Frontend Developer",
    // totalLike: "690",
    title: "FabSight Application in React",
    image: "./projects/fabsight.png",
    f1: "",
    f2: "",
    f3: "",
    f4: "",
    f5: "",
    f6: "",
    f7: "",
    f8: "",
    f9: "",
    f10: "",
    f11: "",
    f12: "",
  },
];
export default Portfolio_data;
