const Portfolio_data = [
  {
    id: 1,
    category: "Backend Developer",
    // totalLike: "Backend",
    title: "Restaurant System Application (Laravel) ",
    image: "./projects/Rest.jpeg",
    f1: "1-The process of creating an account for the customer and enjoying its powers.",
    f2: "2-Store management operations in the restaurant - Management processes for reservations.",
    f3: "3-Make reservations for the customer and create a reservation for the customer in the restaurant.",
    f4: "4-admin login - Accountant login.",
    f5: "5-Operations of adding, modifying, deleting and displaying the types of meals and meals",
    f6: "6-Accounts management operations for accountants.",
    f7: "7-Bring out the statistics for the profit and loss rate in the previous months for the restaurant.",
    f8: "8-Export customer orders invoices.",
    github: "https://github.com/SalahDerbas/RestManagementSystem",
    youtube: "https://www.youtube.com/watch?v=mz_12Ls_fss",
  },
  {
    id: 2,
    category: "Backend Developer",
    // totalLike: "750",
    title: "Real Time Chat Application (Laravel Livewire)",
    image: "./projects/chat.png",
    f1: "1-User logins.",
    f2: "2-Users view of the application.",
    f3: "3-Send a message.",
    f4: "4-Send a picture.",
    f5: "5-Send files",
    f6: "",
    f7: "",
    f8: "",
    github: "https://github.com/SalahDerbas/chat",
    youtube: "https://www.youtube.com/watch?v=FM4cKvFki58",
  },
  {
    id: 3,
    category: "Backend Developer",
    // totalLike: "630",
    title: "Chart Data Visulization Application (Laravel) ",
    image: "./projects/chart.png",

    f1: "1-User logins.",
    f2: "2-Users view of the application.",
    f3: "3-Send a message.",
    f4: "4-Send a picture.",
    f5: "5-Send files",
    f6: "",
    f7: "",
    f8: "",
    github: "https://github.com/SalahDerbas/Chart",
    youtube: "https://www.youtube.com/watch?v=XmSKcVEZV5o",
  },
  {
    id: 4,
    category: "Backend Developer",
    // totalLike: "360",
    title: "Invoicing System Application (Laravel)",
    image: "./projects/invoice.png",
    f1: "1-Client login.",
    f2: "2-View statistical data and control panel.",
    f3: "3-The operations of adding, modifying, deleting and displaying the invoice.",
    f4: "4-Archiving and transferring invoices cases - Upload and delete attachments to invoices.",
    f5: "5-Reporting processes for employees' managers",
    f6: "6-Operations of addition, modification, deletion and presentation to banks and sections of banks.",
    f7: "7-Operations of adding, modifying, deleting, displaying to users and creating accounts for them.",
    f8: "8-Assigning tasks and powers and separating them for assignment to the establishing employees.",
    github: "https://github.com/SalahDerbas/Invoicing_bill",
    youtube: "https://www.youtube.com/watch?v=izzOScdNv5s",
  },
  {
    id: 5,
    category: "Backend Developer",
    // totalLike: "280",
    title: "Rest Full API Application CRUD & JWT (Laravel)",
    image: "./projects/api.webp",
    f1: "1-Create a product.",
    f2: "2-Update a product.",
    f3: "3-View the product.",
    f4: "4-Delete the product.",
    f5: "5-View all products",
    f6: "6-Use JWT of the for authorization and authentication.",
    f7: "",
    f8: "",
    github: "https://github.com/SalahDerbas/RestFull-API",
    youtube: "https://www.youtube.com/watch?v=DwKRFgv_5rY",
  },
  {
    id: 6,
    category: "Backend Developer",
    // totalLike: "690",
    title: "School System Application (Laravel)",
    image: "./projects/schools.webp",
    f1: "",
    f2: "",
    f3: "",
    f4: "",
    f5: "",
    f6: "",
    f7: "",
    f8: "",
    github: "https://github.com/SalahDerbas",
    youtube:
      "https://www.youtube.com/channel/UCEYTgaou2YKbymbC0mUnAhw/featured",
  },
  {
    id: 7,
    category: "Backend Developer",
    // totalLike: "690",
    title: "Portfolio Dynamically Application (Laravel)",
    image: "./projects/portfolio.png",
    f1: "",
    f2: "",
    f3: "",
    f4: "",
    f5: "",
    f6: "",
    f7: "",
    f8: "",
    github: "https://github.com/SalahDerbas/PortfolioDynamic",
    youtube:
      "https://www.youtube.com/channel/UCEYTgaou2YKbymbC0mUnAhw/featured",
  },
  {
    id: 8,
    category: "Frontend Developer",
    // totalLike: "690",
    title: "Chat Application (React & Firebase)",
    image: "./projects/chat React.png",
    f1: "1-Create a user through Google or with his information",
    f2: "2-Report to the manager",
    f3: "3-Send a message, file or photo",
    f4: "4-Show users to the manager",
    f5: "",
    f6: "",
    f7: "",
    f8: "",
    github: "https://github.com/SalahDerbas/Chat_firebas",
    youtube:
      "https://www.youtube.com/channel/UCEYTgaou2YKbymbC0mUnAhw/featured",
  },
  {
    id: 9,
    category: "Frontend Developer",
    // totalLike: "690",
    title: "Shopping View (React)",
    image: "./projects/shopping.jpg",
    f1: "1-Create a product display page",
    f2: "2-Select the product",
    f3: "3-Gather the required products",
    f4: "4-Determining the invoice price",
    f5: "",
    f6: "",
    f7: "",
    f8: "",
    github: "https://github.com/SalahDerbas/ShoppingReact",
    youtube: "https://www.youtube.com/watch?v=eeastWLo-gc",
  },
  {
    id: 10,
    category: "Frontend Developer",
    // totalLike: "690",
    title: "FabSight Application (React)",
    image: "./projects/fabsight.png",
    f1: "",
    f2: "",
    f3: "",
    f4: "",
    f5: "",
    f6: "",
    f7: "",
    f8: "",
    github: "https://github.com/SalahDerbas",
    youtube:
      "https://www.youtube.com/channel/UCEYTgaou2YKbymbC0mUnAhw/featured",
  },
];
export default Portfolio_data;
